### ISSUE TITLE
[Bug]: Skipping Intros in a Sync Play Group causes watch time desync

### ISSUE THREAD

**Issue by Krupski19** [intro-skipper/intro-skipper#339] opened 2024-10-10 11:42 UTC
### Self service debugging

- [X] I use Jellyfin 10.9.11 (or newer) and my permissions are correct

### Describe the bug

When in a watch together group using Jellyfin's Sync Play feature, if one of the members in the group presses on the Skip Intro button when an intro appears, that person will skip the intro while everyone else in the group will continue to watch the intro without it being skipped.  Now the person who skipped the intro will be significantly ahead in the video, and even with Sync Corrections enabled for all users, the time skip will not be corrected unless someone pauses and unpauses the video.

### Jellyfin install method

Ubuntu package install

### Container image/tag or Jellyfin version

Jellyfin 10.9.11

### Operating System

Ubuntu

### Support Bundle

```shell
* Jellyfin version: 10.9.11
* Plugin version: 1.0.0+d3453ad937cc
* Queue contents: 5118 episodes, 375 seasons
* Warnings: `None`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu4)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by jumoog** [comment] 2024-10-10 11:53
duplicate of #257 #127 #87

**Closed by jumoog** 2024-10-10 11:53 UTC
Labels: bug
