### ISSUE TITLE
Restarting app to apply update doesn't erase the previous iteration

### ISSUE THREAD

**Issue by UriSheinman** [intro-skipper/intro-skipper#429] opened 2024-12-23 09:25 UTC
Every now and then i update my plugins and all of them erase their older versions after a restart except intro skip. Is the a plugin side or a server side issue?

**Comment by AbandonedCart** [comment] 2024-12-23 14:22
That isn't a plugin feature, so it's hard to guess the cause. Any reason you skipped the form that might have allowed us to get a better idea of the situation?

**Comment by UriSheinman** [comment] 2024-12-23 15:24
Cause when i tried clicking on it it didn't work... I usually follow the guidelines for this...

**Comment by AbandonedCart** [comment] 2024-12-23 15:56
I can't seem to find an issue with the form, but the jellyfin version, OS, and any logs you have will help to investigate.

**Comment by UriSheinman** [comment] 2024-12-23 17:09
It's been happening since i switched to this version from the confusedpolarbear one, so about a year+... I use windows 10, current version is 10.10.3, don't have logs to provide.

**Comment by AbandonedCart** [comment] 2024-12-23 17:45
And you're sure it was previously removing older versions? I've never seen or heard of that working on anything other than Linux.

A fix for it has been merged for 10.10, but has not yet been released. See https://github.com/jellyfin/jellyfin/pull/13106

**Closed as completed** 2024-12-23 18:08 UTC
