### ISSUE TITLE
[Bug]:  Jellyfin 10.9.0 Not working/

### ISSUE THREAD

**Issue by VampiricAlien** [intro-skipper/intro-skipper#157] opened 2024-05-12 13:47 UTC
### Describe the bug

After opening this issue https://github.com/jellyfin/jellyfin/issues/11563 when scanning it can make jellyfin completely unresponsive and that makes the client crash. I am unsure it's this plugin or Jellyfin.

### Jellyfin installation method

Linux

### Operating System

Ubuntu

### Support Bundle

```shell
* Jellyfin version: 10.9.0
* Plugin version: 0.2.0+1af591c4a48
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```
```


### Jellyfin logs

_No response_

**Comment by AbandonedCart** [comment] 2024-05-12 13:49
Does it work again if you remove the plugin or move it somewhere else?

**Comment by jumoog** [comment] 2024-05-12 13:50
Please provide logs, otherwise I won't be able to see what the problem is.

**Comment by jumoog** [comment] 2024-05-12 13:54
I see you are coming from https://github.com/jellyfin/jellyfin/issues/11563

**Comment by jumoog** [comment] 2024-05-12 13:55
Does the Jellyin hangs without the plugin?

**Comment by jumoog** [comment] 2024-05-12 14:09
I have done a full scan of my 10TB and do not see anything unusual. Whats your ulimit?

**Comment by PeachesMLG** [comment] 2024-05-12 17:51
Is your Jellyfin config files on the same drive as your library?

I had issues with this because the database was on the same HDD as the movies/shows so when that HDD was under heavy load the database became very slow. Moving it over to a separate SSD helped for me

**Comment by AbandonedCart** [comment] 2024-05-12 18:31
It's also good not to have your media on the same drive as the OS

**Comment by jumoog** [comment] 2024-05-12 22:45
It worked before?

**Comment by AbandonedCart** [comment] 2024-05-12 23:06
Did we confirm everything works fine with the plugin removed?

**Comment by AbandonedCart** [comment] 2024-05-12 23:22
I would say to make a smaller library of a handful of items and scan just that with and without the plugin. There is an option in the plugin to specify a library

**Comment by AbandonedCart** [comment] 2024-05-12 23:39
That was actually the one to save the most time.

**Comment by AbandonedCart** [comment] 2024-05-13 00:04
Creating a library prevents having to add, delete, or move any media. It's a bit like a sandbox environment

**Comment by AbandonedCart** [comment] 2024-05-13 00:35
Sounds like they may have been addressing it on their end, too. Speaking of which, you can turn down the processing settings of the plugin, as well. It's only really relative to itself and a few other plugins, but it may help.

**Comment by AbandonedCart** [comment] 2024-05-13 01:40
-1 is usually the fallback value because 0 is technically valid, but it looks like only the episode gets defaulted to 0 unless I missed a line in my search.

**Comment by jumoog** [comment] 2024-05-13 08:00
> I believe there is a bug create new libraries, gave it a try and nothing. We can put this on hold until as you said someone else has the same issue. Wonder if it would be easier in docker.
> 
> This is strange. Disabled plugin, restart and saw this. It downloaded the plugin and installed it. ![plugin area](https://private-user-images.githubusercontent.com/115914075/329889971-a61e3bee-1d38-4f28-8465-5f0b424d813c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODcxNTksIm5iZiI6MTcxNTU4Njg1OSwicGF0aCI6Ii8xMTU5MTQwNzUvMzI5ODg5OTcxLWE2MWUzYmVlLTFkMzgtNGYyOC04NDY1LTVmMGI0MjRkODEzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNzU0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmRkOWYzMDhmYjA1ZTlmYWQxOTU3ZDVhMDdlM2I4MDQ5MWNkZTJjNWJlZjUwZjFkMDhmMWVmZTZiZDgyNDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VO6gsapuGv0uLDgdP-r6tw2xIVf8Q0uy4kp8IpATGVA)

How do you manage to get into this strange state?

If you upgraded to `v10.9.1` and had problems before, you should restore your `10.8` backup first. Some library damage can't be undone.

**Closed as completed** 2024-05-17 13:53 UTC
Labels: bug
